version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodle_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: gunicorn foodle.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=foodle.settings
      - DATABASE_URL=postgres://user:password@db:5432/foodle_db
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
