# Generated by Django 4.2.16 on 2024-10-02 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('upload', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('shop', models.IntegerField(choices=[(0, 'PICARD'), (1, 'FRANCPRIX'), (2, 'LIDLE'), (3, 'CARREFOUR')], default=0, verbose_name='Nom du magasin')),
            ],
        ),
    ]
